CREATE OR REPLACE FORCE VIEW "HR"."EMPLOYEES_DML_V" AS
SELECT "EMPLOYEE_ID",
       "FIRST_NAME",
       "LAST_NAME",
       "EMAIL",
       "PHONE_NUMBER",
       "HIRE_DATE",
       "JOB_ID",
       "SALARY",
       "COMMISSION_PCT",
       "MANAGER_ID",
       "DEPARTMENT_ID"
  FROM EMPLOYEES;

